### ISSUE TITLE
[Bug] v6 can't open file like 'dist/report.html'

### ISSUE THREAD

**Issue by wenfangdu** [sindresorhus/opn-cli#16]
Command:
```bash
open-cli dist/report.html
```
Works in v5, breaks in v6

**Comment by sindresorhus** [comment]
Works fine for me on macOS 11. You haven't really included any useful info for me to debug this. Try to look through https://github.com/sindresorhus/open/issues?q=is:issue+is:open+sort:updated-desc and see if your issue is one of those.

**Comment by Kreozot** [comment]
I confirm this issue on Windows 10 (node 14.15.1)

And yes, it's working pretty well on open-cli 5.0.0. So I suggest considering it as a new Windows-specific bug.

**Comment by Kreozot** [comment]
I was trying to execute `open-cli out/index.html`

`console.log(command, cliArguments, childProcessOptions);` before `childProcess.spawn` in index.js of "open" package shows this:

on open@6.4.0:
```
cmd [ '/c', 'start', '""', '/b', 'out/index.html' ] {}
```
(and this works)

on open@7.3.0:
```
C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell [
  '-NoProfile',
  '-NonInteractive',
  '–ExecutionPolicy',
  'Bypass',
  '-EncodedCommand',
  'UwB0AGEAcgB0ACAAIgBgACIAbwB1AHQALwBpAG4AZABlAHgALgBoAHQAbQBsAGAAIgAiAA=='
] { windowsVerbatimArguments: true }
```
(and this doesn't works)

**Comment by kuzalekon** [comment]
[#214](https://github.com/sindresorhus/open/pull/220) must fix this problem in the `open` library. Then it will be necessary to update this dependency up to the new version.
