### ISSUE TITLE
Use --no-wait as default

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/opn-cli#2]
I actually always use `opn-cli` with the `--no-wait` flag. For instance for opening the finder at certain locations. I don't want to wait untill I close the process. Wouldn't `--no-wait` as default make more sense? Just something I want to discuss :).

// @sindresorhus @kevva

**Comment by sindresorhus** [comment]
Hah, I was thinking about that too yesterday when manually testing this before publishing. Let's do it.

**Comment by kevva** [comment]
Agree. I usually dislike this option ( `--wait` that is) even though it has its use cases.

**Comment by SamVerschueren** [comment]
Alright, will do a PR!
