### ISSUE TITLE
Vulnerability on file-type

### ISSUE THREAD

**Issue by jean-smaug** [sindresorhus/opn-cli#21]
👋 Hello,
There is an issue on the `file-type` dependency.
https://github.com/advisories/GHSA-mhxj-85r3-2x55

Bump dependency is enough

**Comment by sindresorhus** [comment]
The vulnerability does not apply to this package, but sure, I can upgrade dependencies.

**Comment by jean-smaug** [comment]
Thank you @sindresorhus
