### ISSUE TITLE
Question: dependencies

### ISSUE THREAD

**Issue by nikitaeverywhere** [sindresorhus/opn-cli#22]
Hello! Thanks for your tremendous work for open source.

I came across your (kinda) simple package to simply say `open ./file.html` in my npm script and stay cross-platform. I also see quite a simple implementation in `cli.js`.

Bull well why how come this happens:

![image](https://user-images.githubusercontent.com/4989256/229354094-afd24ebf-255f-4de2-bc9e-923c2be9eebc.png)

Can we consider lowering the number of dependencies for the utility that ideally should have none? Any thoughts on it?

As a package downloaded 100M+ times per month it would save so much.

Thanks!

**Comment by nikitaeverywhere** [comment]
Update: the [implementation](https://github.com/sindresorhus/open/blob/main/index.js) is not that simple I agree. Might be, the other thing to consider is to split the functionality into a separate package just for opening files. I'm under the impression of [this](https://dwheeler.com/essays/open-files-urls.html) kind of simplicity needed for the task.

**Comment by sindresorhus** [comment]
Reducing the dependency tree is being worked on: https://github.com/sindresorhus/meow/issues/67 I disagree that this package should have none though.

**Comment by nikitaeverywhere** [comment]
Thanks for letting me know. I didn't say it should have none, I just point out that it downloads half of the internet to open the URL :) Because of `meow`, now makes sense.
